### ISSUE TITLE
Document how to maintain the contact list from the hosts

### ISSUE THREAD

**Issue by daverick** [codebar/barcelona#78]
Add in the documentation and the templates how to actively maintain the contact list we have from the hosts.
propose the usage of FMB (functional mail box) in addition to personal ones

**Comment by amaliacardenas** [comment]
@daverick What is the concept of the functional mail box?

**Comment by daverick** [comment]
a funcional mail box is a email address that is not directed to a person but to a function in a company. like hr@acme.com jobs@aceme.com or barcelona@codebar.io
using such mailbox in complement to the personal one will allow us to keep contact with then companies even when our contact move to another one.

**Comment by loriking** [comment]
@amaliacardenas to draft letter to send to companies 
@ancagabriela to do the documentation and template updates

**Comment by ancagabriela** [comment]
@daverick will contact Kimberley about the emails for the newsletter and to share with her our situation related to getting the functional mailbox because of the people rotation inside companies 
@amaliacardenas will do the draft letter @daverick will review
@ancagabriela https://github.com/codebar/barcelona/blob/master/processes/workshops-preparation/preparing-a-workshop.md https://github.com/codebar/barcelona/tree/master/chapter_assets/email-templates

**Comment by daverick** [comment]
@daverick has updated the email on the codebar website for the mother org.and express the concern with them to use functional email.
@amaliacardenas will do the draft letter @daverick will review

**Comment by loriking** [comment]
Sending holiday greetings to our hosts and update emails if any bounce @jmbriano @amaliacardenas

**Comment by amaliacardenas** [comment]
There are no updates on this issue. I am quite swamped at the moment. If someone else wants to take ownership of this issue it would be helpful.

**Comment by saljuama** [comment]
No updates, @amaliacardenas  will try to work on this
No rush, no priority

**Comment by raquelalvear** [comment]
@amaliacardenas will probably send it next week

**Comment by daverick** [comment]
https://github.com/codebar/barcelona/pull/91 merged!

**Comment by daverick** [comment]
@amaliacardenas will email the hosts.

**Comment by amaliacardenas** [comment]
I emailed all of the hosts that we had on our list. All of the hosts highlighted in red are those whose contact details are no longer valid. The hosts highlighted in green, are those who have been contacted, but we have not gotten a response from them yet. The hosts in white, have valid email addresses. 

Do we want to let hosts know that they can sponsor virtual workshops? Do we want to try to find a sponsor for virtual workshops?

**Comment by amaliacardenas** [comment]
We will email hosts once we create a document for how to sponsor a virtual workshop. We also agreed to see if we can find other people who work at companies with who we no longer have contacts at.

**Comment by saljuama** [comment]
No updates, and that is ok

**Comment by saljuama** [comment]
no updates, and is still ok 🌟

**Comment by daverick** [comment]
no updates, and is still ok 🌟 🙆

**Comment by Klarala13** [comment]
Since we woud like to return to in person workshops we should update the list so we are ready when we go back.
@daverick will go through the list and "ping" the companies to check the status. 
@saljuama knows that Thoughtworks is interested in hosting a workshop. 
@Klarala13 will ask Monica (in, at least, a week) and see if it is possible to start in person. 
Also, it would be good to ask for a generic email from the company so we don´t have to refer to a particular person.

**Comment by daverick** [comment]
@daverick and @amaliacardenas will work between xmas and Reyes on contacting companies to start seeing if they would host some workshop.

**Comment by KimberleyCook** [comment]
The Brighton team sent this newsletter https://us8.campaign-archive.com/?u=b4652d85b385945c79f2ffa2e&id=a30cd4ab7d from our Mailchimp to their previous hosts. We can do the same for all your previous hosts if you'd like?

**Comment by amaliacardenas** [comment]
@daverick updated the host contact list and sent an email to see who is interested in having an in-person workshop. We will wait and see once things get better with COVID to see when we can host an in-person workshop.
