### ISSUE TITLE
on-boarding new organizers

### ISSUE THREAD

**Issue by daverick** [codebar/barcelona#93]

**Comment by saljuama** [comment]
Did some commits into the repository (didn't do PR's because trunk based development for the win) : 

* Added [documentation for the pairing tool](https://github.com/codebar/barcelona/tree/master/tools/pairing-tool)
* Reworked the [monthly meetings process](https://github.com/codebar/barcelona/blob/master/processes/org-monthly-meetings/org-monthly-meetings.md) documentation including the continuous improvement and removing a lot of the repetition and boilerplate
* Improved the [processes index](https://github.com/codebar/barcelona/tree/master/processes) a little bit
* Moved the old meeting minutes outside processes into the [meetings folder](https://github.com/codebar/barcelona/tree/master/organisers_meetings). (do we want to keep those?) 

 Other actions discussed with @amaliacardenas : 
 * Document how to prepare a virtual workshop
 * Review social media usage and documentation (anyone has any suggestion on this? specially around instagram)
 * Finish the account setup for new organisers
 * And schedule onboarding sessions with the new organisers after the accounts are setup!

**Comment by amaliacardenas** [comment]
The only thing pending is to schedule the onboarding. We agreed to create a new issue to review social media use and set up documentation as this warrants a longer discussion.
